version: '3.4'

services:
  gisa_authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APP_INSIGHTS_INSTR_KEY=abd74bbc-44a4-4725-9838-13890489239e
      - AWS_ACCESS_KEY_ID=AKIARQYA547GJHAQR5MU
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=sa-east-1
      - COGNITO_APP_CLIENT_ID=25meblt7cemgtp30gpa9i7tg1d
      - COGNITO_USER_POOL_ID=sa-east-1_Bc7W9doXH
      - COGNITO_APP_CLIENT_SECRET=1pbbvvc2ag0um3brhaf3jrqs1fefbofhsmtgfuj9urhtadjsjqf
      - CONNECTION_STRING=Server=host.docker.internal; Database=GISADatabaseMIC; MultipleActiveResultSets=true; User=sa; Password=Passw0rd!
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  gisa_micapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APP_INSIGHTS_INSTR_KEY=abd74bbc-44a4-4725-9838-13890489239e
      - AWS_ACCESS_KEY_ID=AKIARQYA547GJHAQR5MU
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=sa-east-1
      - COGNITO_APP_CLIENT_ID=25meblt7cemgtp30gpa9i7tg1d
      - COGNITO_USER_POOL_ID=sa-east-1_Bc7W9doXH
      - COGNITO_APP_CLIENT_SECRET=1pbbvvc2ag0um3brhaf3jrqs1fefbofhsmtgfuj9urhtadjsjqf
      - CONNECTION_STRING=Server=host.docker.internal; Database=GISADatabaseMIC; MultipleActiveResultSets=true; User=sa; Password=Passw0rd!
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  gisa_consultschedulerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

