version: '3.4'

services:
  gisa_authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APP_INSIGHTS_INSTR_KEY=SUA_CREDENCIAL
      - AWS_ACCESS_KEY_ID=SUA_CREDENCIAL
      - AWS_SECRET_ACCESS_KEY=SUA_CREDENCIAL
      - AWS_DEFAULT_REGION=sa-east-1
      - COGNITO_APP_CLIENT_ID=25meblt7cemgtp30gpa9i7tg1d
      - COGNITO_USER_POOL_ID=sa-east-1_Bc7W9doXH
      - COGNITO_APP_CLIENT_SECRET=SUA_CREDENCIAL
      - CONNECTION_STRING=Server=host.docker.internal; Database=GISADatabaseMIC; MultipleActiveResultSets=true; User=sa; Password=Passw0rd!
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  gisa_micapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APP_INSIGHTS_INSTR_KEY=SUA_CREDENCIAL
      - AWS_ACCESS_KEY_ID=SUA_CREDENCIAL
      - AWS_SECRET_ACCESS_KEY=SUA_CREDENCIALv
      - AWS_DEFAULT_REGION=sa-east-1
      - COGNITO_APP_CLIENT_ID=25meblt7cemgtp30gpa9i7tg1d
      - COGNITO_USER_POOL_ID=sa-east-1_Bc7W9doXH
      - COGNITO_APP_CLIENT_SECRET=SUA_CREDENCIAL
      - CONNECTION_STRING=Server=host.docker.internal; Database=GISADatabaseMIC; MultipleActiveResultSets=true; User=sa; Password=Passw0rd!
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  gisa_consultschedulerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
